# Generated by Django 2.2.5 on 2020-07-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200706_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest',
            field=models.IntegerField(help_text='How many people will stay?'),
        ),
    ]
